vectors in Rn + vector algebra 

In [23]:
import numpy as np

In [24]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

#### addition & substraction


In [25]:
add = v1 + v2
sub = v1 - v2
print(sub)
print(add)

[-3 -3 -3]
[5 7 9]


#### Magnitude

In [26]:
mag = np.linalg.norm(v1)
print(mag)

3.7416573867739413


#### linear combination of vector

In [27]:
c1, c2 = 2,-1
result = c1 * v1 + c2 * v2
print(result)

[-2 -1  0]


#### linear independance check

In [28]:
A = np.array([[1,2],
              [2,4]])
rank = np.linalg.matrix_rank(A)
if rank < A.shape[1]:
    print("dependant")
else:
    print("Independant")

dependant


#### Orthonormal Vectors

In [29]:
v4 = np.array([1,0])
v5 = np.array([0,1])

dot = np.dot(v4,v5)
norm_v4 = np.linalg.norm(v4)

print("Dot",dot)
print("Norm",norm_v4)

Dot 0
Norm 1.0


### Matrix basics

In [30]:
P = np.array([[1,2],
              [3,4]])

In [31]:
# identity
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [32]:
# Transpose
A.T

array([[1, 2],
       [2, 4]])

#### scalar multiplication

In [33]:
scalar = 2 * P
print (scalar)

[[2 4]
 [6 8]]


#### Determinant

In [34]:
det = np.linalg.det(P)
print(det)

-2.0000000000000004


#### Inverse

In [35]:
np.linalg.inv(P)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [36]:
x = np.array([[1,1],
              [1,2],
              [1,3]])
y = np.array([2,3,4])

theta = np.linalg.inv(x.T.dot(x)) .dot(x.T) .dot(y)
print(theta)

[1. 1.]


In [37]:
S = np.array([[1,2],
              [3,4]])
T = np.array([[5,6],
              [7,8]])

S @ T

array([[19, 22],
       [43, 50]])