### Day 2 math for ml practice


In [2]:
import numpy as np


[1 2 3]


#### Vecror in R3

In [3]:
v = np.array([1,0,-2])
print(v)

[ 1  0 -2]


#### vector in R5

In [4]:
v = np.array([1,2,3,4,5])
print(v)

[1 2 3 4 5]


#### check dimension of vector

In [5]:
v.shape

(5,)

In [6]:
v = np.zeros(3)
print(v)

[0. 0. 0.]


In [9]:
# unit vector (manually)
v = np.array([3,4])
unit_v = v / np.linalg.norm(v)
print(unit_v)

[0.6 0.8]


In [11]:
# vector magnitude (norm)
print(np.linalg.norm(v))

5.0


In [14]:
# random vector in R4 
v = np.random.rand(4)
print(v)

[0.6145573  0.90233828 0.75048974 0.73947041]


In [19]:
# access vector elements 
v = np.array([10,20,30])
print(v[0],v[1])
print(v[0] + v[2])

10 20
40


In [20]:
# negative vector 
v = np.array([1,-2,3])
print(-v)

[-1  2 -3]


In [21]:
# convert list -> vector 
lst = [5,6,7]
v = np.array(lst)
print(v)

[5 6 7]
