### linear span 

##### Ex.1. check if a vector is in the span 

In [4]:
import numpy as np
v1 = np.array([1,0])
v2 = np.array([0,1])

In [5]:
A = np.column_stack([v1,v2])


In [6]:
b_in = np.array([3,-2])
b_out = np.array([0,0,1])

def in_span(A , b, tol = 1e-9):
    x, res , rank, sv = np.linalg.lstsq(A,b, rcond = None)
    residual = np.linalg.norm(A @ x - b)
    return residual < tol , x

ok, coeffs = in_span(A, b_in)
print(f"b_in in spain ? {ok}, coefficient : {coeffs}")

b_in in spain ? True, coefficient : [ 3. -2.]


#### Ex.2. span = column space; rank = dimension of span

In [7]:
P = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [8]:
U,S,Vt = np.linalg.svd(P)
rank = np.sum(S > 1e-9)

col_space_basis = U[:, : rank]
print(rank)
print(np.round(col_space_basis ,3))

2
[[-0.215  0.887]
 [-0.521  0.25 ]
 [-0.826 -0.388]]


In [10]:
# orthonormal


A = np.array([[1,1],
              [1,-1]])

Q, R = np.linalg.qr(A)

print(Q)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [11]:


# Check orthogonality
u = np.array([1, 0])
v = np.array([0, 1])
print(np.dot(u, v))           # 0 → orthogonal ✓
print(np.linalg.norm(u))      # 1 → normal ✓

# QR decomposition → Q has orthonormal columns
A = np.array([[1,2],[3,4],[5,6]], dtype=float)
Q, R = np.linalg.qr(A)
print(Q.T @ Q)                # ≈ Identity matrix ✓

# Gram-Schmidt via QR (built-in)
print(np.round(Q, 3))

0
1.0
[[1.00000000e+00 5.55111512e-17]
 [5.55111512e-17 1.00000000e+00]]
[[-0.169  0.897]
 [-0.507  0.276]
 [-0.845 -0.345]]
