A vector is a mathematical object that encodes a mathematical object that encodes a length & direction 

more formally they are elements of a vector space, a collection of object that is closed under an addition rule
& rule for multiplication by scalars 

a vector is often represented as 1-dimendional (1-D) array of numbers reffered to as componant ant its displayed either in column form or row form

In [1]:
import numpy as np 

In [2]:
v = np.array([1,-1,3])
w = np.array([2,5,2])

In [3]:
print(v+w)

[3 4 5]


In [4]:
print(v-w)

[-1 -6  1]


### scalar multiplication

In [5]:
print(3*v)

[ 3 -3  9]


### find length of v

In [6]:
print(np.linalg.norm(v))

3.3166247903554


### dot product

In [7]:
print(np.dot(v,w))

3
